version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  labels:
    - "dependencies"
    - "v2.x"
  schedule: 
    interval: "weekly"

# branch - v1.x
- package-ecosystem: "maven"
  directory: "/"
  labels:
    - "dependencies"
    - "v1.x"
  target-branch: "v1.x"
  schedule:
    interval: "weekly"

