version: 2
updates:
  # branch - master
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
      - "v3.x"
    target-branch: "master"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
  # branch - v2.x
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
      - "v2.x"
    target-branch: "v2.x"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
  # branch - v1.x
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
      - "v1.x"
    target-branch: "v1.x"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
