version: 2
updates:
  # branch - master
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
      - "v3.x"
    target-branch: "master"
    schedule:
      interval: "weekly"

permissions:
  contents: write
  pull-requests: write